### ISSUE TITLE
Node engine >= 7.6?

### ISSUE THREAD

**Issue by tkambler** [kei-ito/rollup-plugin-glob-import#3]
Is that really necessary? I'm on 6.11.3 LTS.

**Comment by kei-ito** [comment]
That is really necessary **now** because it uses *async functions* available on v7.6.0 or later. [v7.6.0](https://nodejs.org/en/blog/release/v7.6.0/) updated V8 to [5.5 which supports *async functions*](https://v8project.blogspot.jp/2016/10/v8-release-55.html). I've created a new branch to test it. Here's the results:

- https://travis-ci.org/kei-ito/rollup-plugin-glob-import/builds/275715410

Thank you for your question. IMO, the plugin should support older versions until [EOL](https://github.com/nodejs/LTS). I'll update it on this branch to support versions listed in the results.

**Comment by kei-ito** [comment]
I've published v0.0.8 which works on Node>=6.

**Comment by tkambler** [comment]
Thank you.
